create table language (id integer generated by default as identity, title varchar(255) not null, primary key (id));

insert into language values (1, 'Pascal'),
                            (2, 'C'),
                            (3, 'C++'),
                            (4, 'JavaScript'),
                            (5, 'PHP'),
                            (6, 'Python'),
                            (7, 'Java'),
                            (8, 'Haskel'),
                            (9, 'Clojure'),
                            (10, 'Prolog'),
                            (11, 'Scala');

create table admin
(
    id           bigint generated by default as identity
        primary key,
    passwordhash varchar(255),
    salt         varchar(255),
    username     varchar(255)
);

insert into admin values (1, 'Jba8eMQHZh4A3y/zRu6jbBata8IS6qfW9y+zFjDWW3I=', 'xoHqzZfW0lEXZoKTBl/fTw==',
                          'admin1');
-- 123456