create table language (id integer generated by default as identity, title varchar(255) not null, primary key (id));

insert into language values (1, 'Pascal'),
                            (2, 'C'),
                            (3, 'C++'),
                            (4, 'JavaScript'),
                            (5, 'PHP'),
                            (6, 'Python'),
                            (7, 'Java'),
                            (8, 'Haskel'),
                            (9, 'Clojure'),
                            (10, 'Prolog'),
                            (11, 'Scala');